version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        patterns:
          - "*"

