#![feature(cfg_version)]
#![cfg_attr(not(version("1.88.0")), feature(let_chains))]

#[cfg(feature = "dhat-heap")]
#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;

use human_panic::{Metadata, setup_panic};
#[cfg(all(feature = "jemallocator", not(feature = "dhat-heap")))]
use tikv_jemallocator::Jemalloc;

#[cfg(all(feature = "jemallocator", not(feature = "dhat-heap")))]
#[global_allocator]
static GLOBAL: Jemalloc = Jemalloc;

extern crate clash_lib as clash;

use anyhow::{Context, anyhow};
use base64::{Engine, engine::general_purpose::STANDARD};
use clap::Parser;
use clash::TokioRuntime;
use std::{
    io::{Read, Write},
    path::{Path, PathBuf},
    process::exit,
};
use time::{OffsetDateTime, macros::format_description};

const DEFAULT_CONFIG_FILE: &str = "config.yaml";
const DEFAULT_CONFIG_CONTENT: &str = "mixed-port: 7890";

#[derive(Parser)]
#[clap(author, about, long_about = None)]
struct Cli {
    #[clap(short, long, value_parser, value_name = "DIRECTORY")]
    directory: Option<PathBuf>,

    #[clap(
        short,
        long,
        visible_short_aliases = ['f'], // -f is used by clash, it is a compatibility option
        value_parser,
        value_name = "FILE",
        help = "Specify configuration file"
    )]
    config: Option<PathBuf>,
    #[clap(long = "mihomo-file", hide = true, value_parser, value_name = "FILE")]
    mihomo_file: Option<PathBuf>,
    #[clap(long = "mihomo-config", hide = true, value_name = "BASE64")]
    mihomo_config: Option<String>,
    #[clap(
        short = 't',
        long,
        value_parser,
        default_value = "false",
        help = "Test configuration and exit"
    )]
    test_config: bool,
    #[clap(
        short,
        long,
        visible_short_aliases = ['V'],
        value_parser,
        default_value = "false",
        help = "Print clash-rs version and exit"
    )]
    version: bool,
    #[clap(short, long, help = "Additionally log to file")]
    log_file: Option<String>,

    #[clap(
        long,
        value_parser,
        default_value = "false",
        help = "Enable crash report to help improve clash"
    )]
    help_improve: bool,

    #[clap(
        long,
        visible_aliases = ["ext-ctl-pipe", "ext-ctl-unix"],
        value_parser,
        value_name = "IPC_PATH",
        help = "Specify the IPC path for the controller"
    )]
    controller_ipc: Option<String>,

    #[clap(
        long,
        value_parser,
        default_value = "true",
        help = "Enable compatibility mode, which make behaviors more consistent \
                with mihomo but may cause some issues. It is recommended to enable \
                this if you are using clash verge."
    )]
    compatibility: bool,
}

fn main() -> anyhow::Result<()> {
    #[cfg(feature = "dhat-heap")]
    let _profiler = dhat::Profiler::new_heap();

    // Those arguments are for compatibility with `mihomo`
    // Technically, I do not think `mihomo` is a modern/standard POSIX Cli program
    let args = preprocess_args(std::env::args());
    let cli = Cli::parse_from(args);

    if cli.version {
        println!(
            "{} {}",
            env!("CARGO_PKG_NAME"),
            env!("CLASH_VERSION_OVERRIDE") // Generated by build.rs
        );
        exit(0)
    }

    let config_input = match ConfigInput::resolve(&cli) {
        Ok(config_input) => config_input,
        Err(err) => {
            print_mihomo_log("fatal", &err.to_string());
            exit(1);
        }
    };

    if let Err(err) = config_input.ensure_file() {
        print_mihomo_log("fatal", &err.to_string());
        exit(1);
    }

    if cli.test_config {
        match config_input.try_parse() {
            Ok(_) => {
                print_test_success(&config_input);
                exit(0);
            }
            Err(e) => {
                print_mihomo_log("error", &e.to_string());
                print_test_failure(&config_input);
                exit(1);
            }
        }
    }

    // NOTE: set this up before Sentry
    setup_panic!(
        Metadata::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"))
            .authors(env!("CARGO_PKG_AUTHORS"))
            .homepage(env!("CARGO_PKG_HOMEPAGE"))
            .support(
                "Open an issue on GitHub: https://github.com/Watfaq/clash-rs/issues"
            )
    );

    let mut _guard = None;
    if cli.help_improve {
        _guard = Some(sentry::init((
            env!("SENTRY_DSN"),
            sentry::ClientOptions {
                release: sentry::release_name!(),
                ..Default::default()
            },
        )));
    }

    let mut config = config_input.try_parse()?;

    config.general.controller.external_controller_ipc = cli.controller_ipc;

    if cli.compatibility {
        println!(
            "Compatibility mode enabled. This may cause some issues, but it is \
             recommended to enable this if you are using clash verge."
        );
        if let Some(dir) = &cli.directory {
            // Canonicalize to an absolute path before changing the process cwd.
            // If `dir` is relative (e.g. `./clash-bin/tests/data/config`),
            // calling set_current_dir then passing the same relative string as
            // `cwd` to start_scaffold would cause paths like
            // `cwd.join("Country.mmdb")` to be resolved from the *new* process
            // cwd, doubling the directory segments and producing a path that
            // doesn't exist (os error 2).
            let abs = std::fs::canonicalize(dir)?;
            std::env::set_current_dir(&abs)?;
        }
        if config.general.mmdb.is_none() {
            config.general.mmdb = Some("Country.mmdb".to_string());
        }
        if config.general.geosite.is_none() {
            config.general.geosite = Some("geosite.dat".to_string());
        }
    }

    // When compatibility mode called set_current_dir the process cwd is
    // already correct; pass None so start_scaffold uses "." (= the new cwd)
    // rather than the original relative cli.directory which would be resolved
    // from the wrong base.
    let cwd = if cli.compatibility && cli.directory.is_some() {
        None
    } else {
        cli.directory.map(|x| x.to_string_lossy().to_string())
    };

    clash::start_scaffold(clash::Options {
        config: clash::Config::Internal(config),
        cwd,
        rt: Some(TokioRuntime::MultiThread),
        log_file: cli.log_file,
    })
    .inspect_err(|err| eprintln!("Failed to start clash: {err}"))?;
    Ok(())
}

enum ConfigInput {
    File { path: PathBuf, display_path: String },
    Bytes { content: String },
}

impl ConfigInput {
    fn resolve(cli: &Cli) -> anyhow::Result<Self> {
        if let Some(config) = cli.mihomo_config.as_deref() {
            return decode_config(config);
        }
        if let Ok(config) = std::env::var("CLASH_CONFIG_STRING") {
            return decode_config(&config);
        }

        if let Some(file) = cli.mihomo_file.as_ref() {
            return resolve_mihomo_file(file);
        }

        if let Some(file) = std::env::var_os("CLASH_CONFIG_FILE") {
            return resolve_mihomo_file(&PathBuf::from(file));
        }

        let current_dir =
            std::env::current_dir().context("get current directory")?;
        let home_dir = cli
            .directory
            .clone()
            .or_else(|| std::env::var_os("CLASH_HOME_DIR").map(PathBuf::from));
        let directory = match home_dir {
            Some(directory) if directory.is_absolute() => directory,
            Some(directory) => current_dir.join(directory),
            None => current_dir,
        };
        let config = cli
            .config
            .as_ref()
            .cloned()
            .unwrap_or_else(|| PathBuf::from(DEFAULT_CONFIG_FILE));
        let path = if config.is_absolute() {
            config
        } else {
            directory.join(config)
        };
        Ok(Self::from_file_path(path))
    }

    fn from_file_path(path: PathBuf) -> Self {
        let path =
            absolutize(path).unwrap_or_else(|_| PathBuf::from(DEFAULT_CONFIG_FILE));
        let display_path = path.to_string_lossy().to_string();
        Self::File { path, display_path }
    }

    fn ensure_file(&self) -> anyhow::Result<()> {
        let Self::File { path, .. } = self else {
            return Ok(());
        };
        if path.exists() {
            return Ok(());
        }
        if let Some(parent) = path.parent()
            && !parent.as_os_str().is_empty()
        {
            std::fs::create_dir_all(parent).with_context(|| {
                format!(
                    "default profile directory cannot be created: {}",
                    parent.display()
                )
            })?;
        }
        let mut config_file = std::fs::File::create(path).with_context(|| {
            format!("default profile cannot be created: {}", path.display())
        })?;
        config_file
            .write_all(DEFAULT_CONFIG_CONTENT.as_bytes())
            .with_context(|| {
                format!("default profile cannot be written: {}", path.display())
            })?;
        Ok(())
    }

    fn try_parse(&self) -> clash::Result<clash::ClashRuntimeConfig> {
        match self {
            Self::File { path, display_path } => {
                if std::fs::metadata(path).map(|metadata| metadata.len() == 0)? {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("configuration file {display_path} is empty"),
                    )
                    .into());
                }
                clash::Config::File(path.to_string_lossy().to_string()).try_parse()
            }
            Self::Bytes { content } => {
                clash::Config::Str(content.clone()).try_parse()
            }
        }
    }
}

fn preprocess_args(args: impl IntoIterator<Item = String>) -> Vec<String> {
    args.into_iter()
        .map(|arg| match arg.as_str() {
            "-ext-ctl-unix" => "--ext-ctl-unix".to_string(),
            "-ext-ctl-pipe" => "--ext-ctl-pipe".to_string(),
            "-config" => "--mihomo-config".to_string(),
            "-f" => "--mihomo-file".to_string(),
            _ if arg.starts_with("-config=") => {
                arg.replacen("-config=", "--mihomo-config=", 1)
            }
            _ if arg.starts_with("-f=") => arg.replacen("-f=", "--mihomo-file=", 1),
            _ if arg.starts_with("-f") && arg.len() > 2 => {
                format!("--mihomo-file={}", &arg[2..])
            }
            _ => arg,
        })
        .collect()
}

fn decode_config(config: &str) -> anyhow::Result<ConfigInput> {
    let content = STANDARD
        .decode(config)
        .map_err(|err| anyhow!("decode config: {err}"))?;
    let content = String::from_utf8_lossy(&content).into_owned();
    Ok(ConfigInput::Bytes { content })
}

fn resolve_mihomo_file(file: &Path) -> anyhow::Result<ConfigInput> {
    if file == Path::new("-") {
        let mut content = String::new();
        std::io::stdin()
            .read_to_string(&mut content)
            .context("read configuration from stdin")?;
        if !content.is_empty() {
            return Ok(ConfigInput::Bytes { content });
        }
        return Ok(ConfigInput::from_file_path(PathBuf::from(
            DEFAULT_CONFIG_FILE,
        )));
    }
    Ok(ConfigInput::from_file_path(file.to_path_buf()))
}

fn absolutize(path: PathBuf) -> anyhow::Result<PathBuf> {
    if path.is_absolute() {
        Ok(path)
    } else {
        Ok(std::env::current_dir()
            .context("get current directory")?
            .join(path))
    }
}

fn print_test_success(input: &ConfigInput) {
    match input {
        ConfigInput::File { display_path, .. } => {
            println!("configuration file {display_path} test is successful");
        }
        ConfigInput::Bytes { .. } => {
            println!("configuration file {DEFAULT_CONFIG_FILE} test is successful");
        }
    }
}

fn print_test_failure(input: &ConfigInput) {
    match input {
        ConfigInput::File { display_path, .. } => {
            println!("configuration file {display_path} test failed");
        }
        ConfigInput::Bytes { .. } => {
            println!("configuration test failed");
        }
    }
}

fn print_mihomo_log(level: &str, msg: &str) {
    let format = format_description!(
        "[year]-[month]-[day]T[hour]:[minute]:[second].[subsecond \
         digits:9][offset_hour sign:mandatory]:[offset_minute]"
    );
    let timestamp = OffsetDateTime::now_local()
        .unwrap_or_else(|_| OffsetDateTime::now_utc())
        .format(format)
        .unwrap_or_else(|_| "1970-01-01T00:00:00.000000000+00:00".to_string());
    println!(
        "time=\"{}\" level={} msg=\"{}\"",
        timestamp,
        level,
        escape_logrus_text(msg)
    );
}

fn escape_logrus_text(msg: &str) -> String {
    msg.chars().fold(String::new(), |mut escaped, ch| {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
        escaped
    })
}
