[build]
target-dir = "target"
rustflags = ["--cfg", "tokio_unstable"]
#rustc-wrapper = "sccache"

[env]
SENTRY_DSN = { value = "PLEASE DEFINE AT COMPILE TIME" }
RUSTC_BOOTSTRAP = { value = "1" }

[target.x86_64-pc-windows-msvc]
linker = "link.exe"
rustflags = ["-C", "link-arg=/threads:0"]