name: CI

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: rust-proxy/workflows/.github/workflows/rust-build.yml@v1.0.4
    with:
      rust-toolchain: "stable"
      packages: "clash-rs"
      target-config-file: ".github/target.toml"
      rustflags: ""
      enable-tmate: true

  release:
    name: Release
    needs: [build]
    uses: rust-proxy/workflows/.github/workflows/release-publish.yml@v1.0.4
    with:
      cliff-config: '.github/cliff.toml'

  docker:
    name: Docker
    needs: [build]
    uses: rust-proxy/workflows/.github/workflows/docker-publish.yml@v1.0.4
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: '.github/Dockerfile'
      image-name: 'clash-rs'
      platforms: 'linux/amd64,linux/arm64'
      binary-dir: './packages'
      server-binary-amd64: 'bin-x86_64-linux-musl'
      server-binary-arm64: 'bin-aarch64-linux-musl'
