name: CI

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: rust-proxy/workflows/.github/workflows/rust-build.yml@main
    with:
      rust-toolchain: "stable"
      packages: "clash-rs"
      target-config-file: ".github/target.toml"
      rustflags: ""
      enable-tmate: true
      only-clippy-tests-on-pr: true

  release:
    name: Release
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')))
    needs: [build]
    uses: rust-proxy/workflows/.github/workflows/release-publish.yml@main
    with:
      cliff-config: '.github/cliff.toml'
      create-latest-on-push: true

  docker:
    name: Docker
    needs: [build]
    uses: rust-proxy/workflows/.github/workflows/docker-publish.yml@main
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker-file: '.github/Dockerfile'
      image-name: 'clash-rs'
      platforms: 'linux/amd64,linux/arm64'
      binary-dir: './packages'
      server-binary-amd64: 'clash-rs-x86_64-unknown-linux-musl'
      server-binary-arm64: 'clash-rs-aarch64-unknown-linux-musl'