name: CI (reusable)

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    uses: rust-proxy/workflows/.github/workflows/rust-build-extended.yml@main
    with:
      packages: "clash-rs"
      package-name: "clash"
      image-name: "clash-rs"
      registry: "ghcr.io"
      rust-toolchain: "stable"
      retention-days: 1
